//! bsv-low #499: the fixture D1 of the budget tier (`make ci-d1-budget`, `tools/lane-499`).
//!
//! Prints one SQL script to stdout: the overlay's PRODUCTION schema (the migration list applied to real SQLite
//! exactly as the overlay's runner does, then dumped from `sqlite_master`, so the script carries no re-run ALTER
//! that `wrangler d1 execute` would refuse) and the fixture rows, every row first executed against that schema
//! here (a row the schema refuses fails this program, never the tier). The tier loads it with
//! `wrangler d1 execute low-overlay-db --local --persist-to <dir> --file <script>` and serves the app layer over it.
//!
//! The fixture: identity A holds `A_POTS` unspent pots (the `/owed`, `/results`, `/pots-view`, `/utxo-status`
//! scenarios), identity B holds `B_POTS` (the shed leg drives B's recompute, so A's window is untouched), and
//! `NOISE` strangers hold one pot each with both seats' party rows. The noise is what makes the ceilings mean
//! something: a query that loses its index reads the strangers' rows and reds by its scenario's name. No pot is
//! spent and no hop is filed, so no recompute reaches for a courier (the tier is network-free).

use bsv_overlay_cloudflare::d1::OVERLAY_MIGRATIONS;
use rusqlite::Connection;

const A_POTS: u32 = 8;
const B_POTS: u32 = 2;
/// The strangers (`D1_BUDGET_NOISE` overrides it, to see which route's rows grow with the user count).
const NOISE: u32 = 300;

/// Identity A (the scenarios') and B (the shed leg's), lowercase compressed keys.
const ID_A: &str = "02a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1";
const ID_B: &str = "02b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2";

fn pot_txid(owner: char, i: u32) -> String {
    format!("{owner}{owner}{i:062x}")
}

fn opponent(i: u32) -> String {
    format!("03{i:064x}")
}

fn main() {
    let conn = Connection::open_in_memory().expect("open in-memory sqlite");
    for sql in OVERLAY_MIGRATIONS {
        if let Err(e) = conn.execute_batch(sql) {
            let msg = e.to_string().to_ascii_lowercase();
            assert!(msg.contains("duplicate column"), "production migration failed under real SQLite: {e}\n{sql}");
        }
    }
    let mut out = String::from("-- bsv-low #499: the budget tier's fixture D1 (generated by `cargo run --example d1_budget_seed`)\n");
    let mut stmt = conn
        .prepare("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%' ORDER BY rowid")
        .expect("schema read");
    let schema: Vec<String> = stmt.query_map([], |r| r.get::<_, String>(0)).expect("schema rows").map(|r| r.expect("schema row")).collect();
    for s in schema {
        out.push_str(&s);
        out.push_str(";\n");
    }

    let now_s = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).expect("clock").as_secs();
    let mut rows: Vec<String> = Vec::new();
    let mut pot = |owner: char, identity: &str, i: u32| {
        let txid = pot_txid(owner, i);
        let opp = opponent(i + if owner == 'c' { 0 } else { 100_000 });
        let game = format!("{owner}0{i:062x}");
        rows.push(format!(
            "INSERT INTO pot_records (txid, outputIndex, spent, createdAt) VALUES ('{txid}', 0, 0, {now_s})"
        ));
        for (k, (me, them)) in [(identity, opp.as_str()), (opp.as_str(), identity)].into_iter().enumerate() {
            rows.push(format!(
                "INSERT INTO potparty_records (identity, opponentIdentity, gameId, potTxid, potVout, recoveryHeight, sigHex, txid, outputIndex, createdAt) \
                 VALUES ('{me}', '{them}', '{game}', '{txid}', 0, 958846, '3045ab', '{owner}{k}{i:062x}', 0, {now_s})"
            ));
        }
    };
    for i in 0..A_POTS {
        pot('a', ID_A, i);
    }
    for i in 0..B_POTS {
        pot('b', ID_B, i);
    }
    let noise: u32 = std::env::var("D1_BUDGET_NOISE").ok().and_then(|v| v.parse().ok()).unwrap_or(NOISE);
    for i in 0..noise {
        let stranger = format!("02{i:064x}");
        pot('c', &stranger, i);
    }
    for r in &rows {
        conn.execute(r, []).unwrap_or_else(|e| panic!("the fixture row is refused by the production schema: {e}\n{r}"));
        out.push_str(r);
        out.push_str(";\n");
    }
    print!("{out}");
}
