//! Markdown report generator.

use crate::{client::Captured, corpus::Entry, differ::Outcome, Args};
use anyhow::Result;
use std::{fmt::Write as _, path::Path};

pub fn write(
    path: &Path,
    args: &Args,
    results: &[(Entry, Captured, Captured, Outcome)],
) -> Result<()> {
    let reds: Vec<_> = results.iter().filter(|(_, _, _, o)| !o.matches).collect();
    let greens = results.len() - reds.len();

    let mut md = String::new();
    writeln!(md, "# PARITY_REPORT")?;
    writeln!(md)?;
    writeln!(
        md,
        "Generated by `parity-harness` at UTC now. Exit status: **{}**",
        if reds.is_empty() { "GREEN" } else { "RED" }
    )?;
    writeln!(md)?;
    writeln!(md, "- TS reference: `{}`", args.ts)?;
    writeln!(md, "- Rust target: `{}`", args.rust)?;
    writeln!(md, "- Corpus: `{}`", args.corpus.display())?;
    writeln!(
        md,
        "- Entries: **{}** total — **{} green**, **{} red**",
        results.len(),
        greens,
        reds.len()
    )?;
    writeln!(md)?;

    writeln!(md, "## Summary")?;
    writeln!(md)?;
    writeln!(
        md,
        "| Status | Name | Method | Path | TS status | Rust status |"
    )?;
    writeln!(md, "|---|---|---|---|---|---|")?;
    for (entry, ts, rust, outcome) in results {
        let tag = if outcome.matches { "✅" } else { "❌" };
        writeln!(
            md,
            "| {} | {} | {} | `{}` | {} | {} |",
            tag, entry.name, entry.method, entry.path, ts.status, rust.status
        )?;
    }
    writeln!(md)?;

    if reds.is_empty() {
        writeln!(md, "All entries match. 🎯")?;
    } else {
        writeln!(md, "## Divergences")?;
        writeln!(md)?;
        for (entry, ts, rust, outcome) in reds {
            writeln!(
                md,
                "### ❌ `{}` — {} `{}`",
                entry.name, entry.method, entry.path
            )?;
            writeln!(md)?;
            writeln!(md, "- Source: `{}`", entry.source)?;
            if let Some(note) = &entry.note {
                writeln!(md, "- **Note**: {note}")?;
            }
            writeln!(
                md,
                "- Status: ts={} rust={} — {}",
                ts.status,
                rust.status,
                if outcome.status_matches {
                    "match"
                } else {
                    "**MISMATCH**"
                }
            )?;
            writeln!(
                md,
                "- Content-Type: {}",
                if outcome.content_type_matches {
                    "match"
                } else {
                    "**MISMATCH**"
                }
            )?;
            writeln!(
                md,
                "- Body: {}",
                if outcome.body_matches {
                    "match"
                } else {
                    "**MISMATCH**"
                }
            )?;
            if let Some(err) = &ts.error {
                writeln!(md, "- ts error: `{}`", err)?;
            }
            if let Some(err) = &rust.error {
                writeln!(md, "- rust error: `{}`", err)?;
            }
            writeln!(md)?;
            if !outcome.body_diff.is_empty() {
                writeln!(md, "<details><summary>body diff (canonicalised)</summary>")?;
                writeln!(md)?;
                writeln!(md, "```diff")?;
                md.push_str(&outcome.body_diff);
                writeln!(md, "```")?;
                writeln!(md)?;
                writeln!(md, "</details>")?;
                writeln!(md)?;
            }
        }
    }

    std::fs::write(path, md)?;
    Ok(())
}
